package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"
	"go-ent-spike/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	// この部分を生成したい
	usr, err := r.client.User.
		Create().
		SetName(input.Name).
		SetAge(input.Age).
		Save(ctx)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:   usr.ID.String(),
		Name: input.Name,
		Age:  input.Age,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
